version: '3.4'
services:
  nerfw_server:
    environment:
        - CLIENT_ID=${CLIENT_ID}
        - CLIENT_SECRET=${CLIENT_SECRET}
    build:
      context: "."
    ports:
      - "8080:5000"
    networks:
      - mynetwork
  tests:
    environment:
        - CLIENT_ID=${CLIENT_ID}
        - CLIENT_SECRET=${CLIENT_SECRET}
    build:
      context: "./tests/integration_testing"
    ports:
      - "9999:5000"
    depends_on:
      - "nerfw_server"
    networks:
      - mynetwork
networks:
  mynetwork:
      driver: bridge