name: Build and Publish

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  BuildDocs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.x'

      - name: Build Docker Image
        run: |
          docker build -t nerfw:latest -f build.dockerfile .

      - name: Create Docker container
        run: |
          docker create --name temp_container nerfw:latest

      - name: Copy files from Docker container
        run: |
          docker cp temp_container:/app/docs /docs

      - name: Commit and push files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add files from Docker container"
          git push origin HEAD:${{ github.head_ref }}