name: Build and Publish

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  BuildDocs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.x'
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t nerfw:latest -f build.dockerfile .

      - name: Publish on PyPi
        run: |
          docker run nerfw:latest python -m twine upload -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} --repository pypi dist/*