name: Code check

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - master

jobs:
  PylintCheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.x'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Running Pylint check
        run: |
          pylint $(git ls-files '*.py')

  UnitTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.x'

      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Check output
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch
          git checkout test_branch
          docker-compose up --build --remove-orphans --force-recreate --abort-on-container-exit
        env:
          BRUNCH_NAME: ${{ steps.vars.outputs.short_ref }}
