name: Test Coverage
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - Development_branch

jobs:
  GenerateBadge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.x'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage-badge
          pip install .
      - name: Generate Badge
        run: |
          coverage run -m unittest discover
          coverage-badge -o tests/coverage.svg
      - name: Commit and push if it's not a pull request
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add tests/coverage.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update coverage badge"
          git push